### PR TITLE
fix connection issue when user force move bot to another channel

### LINKED ISSUE #1553: Force move to another voice channel is not handled
### **Git commit reference**
894c18f65c713bb36b63031598142e4789226062

### **Describe the bug**
Moving a robot to another voice channel when streaming audio like shown in the image is not supported

Image

The following may occur:
<details>
<summary>robot move to target channel first and then move back but the voice connect in program is lost, expand for log</summary>

```text
[2026-02-26 14:19:36] DEBUG: Cluster: 996 of 1000 session starts remaining
[2026-02-26 14:19:36] INFO: Auto Shard: Bot requires 1 shard
[2026-02-26 14:19:36] DEBUG: Starting with 1 shards...
[2026-02-26 14:19:36] DEBUG: Connecting new session...
[2026-02-26 14:19:36] INFO: Shard id 0 (1/1) ready!
[2026-02-26 14:19:36] DEBUG: Resume URL for session bc1e608b55ebeb814c56b57830168c0c is wss://gateway-us-east1-b.discord.gg (host: gateway-us-east1-b.discord.gg)
[2026-02-26 14:19:41] DEBUG: Shards started.
[2026-02-26 14:19:45] DEBUG: Sending op 4 to join VC, guild 414647568111239169 channel 1464859146804396157 WITH DAVE
[2026-02-26 14:19:47] DEBUG: Connecting voice for guild 414647568111239169 channel 1464859146804396157
[2026-02-26 14:19:47] DEBUG: Connecting new voice session (DAVE: Enabled)...
[2026-02-26 14:19:47] DEBUG: Voice websocket established; UDP endpoint: 104.29.158.39:19312 [ssrc=3213] with 2 modes
[2026-02-26 14:19:47] DEBUG: New of clients in voice channel: 1 total is 1
[2026-02-26 14:19:48] DEBUG: Creating a new MLS session
[2026-02-26 14:19:48] DEBUG: Resetting MLS session
[2026-02-26 14:19:48] DEBUG: Initializing MLS session with protocol version 1 and group ID 1464859146804396157
[2026-02-26 14:19:48] DEBUG: Created MLS leaf node
[2026-02-26 14:19:48] DEBUG: Cannot create MLS group without external sender
[2026-02-26 14:19:48] DEBUG: voice_client_dave_mls_external_sender
[2026-02-26 14:19:48] DEBUG: Unmarshalling MLS external sender
[2026-02-26 14:19:48] DEBUG: Creating a pending MLS group
[2026-02-26 14:19:48] DEBUG: Created a pending MLS group
[2026-02-26 14:19:48] DEBUG: voice_client_dave_mls_proposals
[2026-02-26 14:19:48] DEBUG: Processing MLS proposals message of 498 bytes
[2026-02-26 14:19:48] DEBUG: Prepared commit/welcome/next state for MLS group from received proposals
[2026-02-26 14:19:48] DEBUG: voice_client_dave_announce_commit_transition
[2026-02-26 14:19:48] DEBUG: Processing commit
[2026-02-26 14:19:48] DEBUG: Successfully processed MLS commit, updating state; our leaf index is 0; current epoch is 1
[2026-02-26 14:19:48] DEBUG: process_mls_group_rosters of size: 2
[2026-02-26 14:19:48] DEBUG: Added user to MLS Group: 414646792567914506
[2026-02-26 14:19:48] DEBUG: Added user to MLS Group: 1445451591900463288
[2026-02-26 14:19:48] DEBUG: Ready to execute transition 0
[2026-02-26 14:19:48] DEBUG: Updating MLS ratchets for 2 user(s)
[2026-02-26 14:19:48] DEBUG: Inserting decryptor key ratchet for NEW user: 414646792567914506, protocol version: 1
[2026-02-26 14:19:48] DEBUG: Setting key ratchet for sending audio...
[2026-02-26 14:19:48] INFO: New E2EE Privacy Code: 28731 03583 32942 30453 15248 30985 
[2026-02-26 14:19:50] DEBUG: Retrieving key for generation 0 from hash ratchet
[2026-02-26 14:20:00] DEBUG: Disconnecting voice, guild: 414647568111239169
LOOP FINISHED SINCE VC IS UNAVAILABLE
[2026-02-26 14:20:08] DEBUG: Sending op 4 to join VC, guild 414647568111239169 channel 1464859146804396157 WITH DAVE
[2026-02-26 14:20:10] DEBUG: Connecting voice for guild 414647568111239169 channel 1464859146804396157
[2026-02-26 14:20:10] DEBUG: Connecting new voice session (DAVE: Enabled)...
[2026-02-26 14:20:10] DEBUG: Voice websocket established; UDP endpoint: 104.29.158.39:19312 [ssrc=3216] with 2 modes
[2026-02-26 14:20:11] DEBUG: New of clients in voice channel: 1 total is 1
[2026-02-26 14:20:11] DEBUG: Creating a new MLS session
[2026-02-26 14:20:11] DEBUG: Resetting MLS session
[2026-02-26 14:20:11] DEBUG: Initializing MLS session with protocol version 1 and group ID 1464859146804396157
[2026-02-26 14:20:11] DEBUG: Created MLS leaf node
[2026-02-26 14:20:11] DEBUG: Cannot create MLS group without external sender
[2026-02-26 14:20:11] DEBUG: voice_client_dave_mls_external_sender
[2026-02-26 14:20:11] DEBUG: Unmarshalling MLS external sender
[2026-02-26 14:20:11] DEBUG: Creating a pending MLS group
[2026-02-26 14:20:11] DEBUG: Created a pending MLS group
[2026-02-26 14:20:11] DEBUG: voice_client_dave_mls_proposals
[2026-02-26 14:20:11] DEBUG: Processing MLS proposals message of 498 bytes
[2026-02-26 14:20:11] DEBUG: Prepared commit/welcome/next state for MLS group from received proposals
[2026-02-26 14:20:11] DEBUG: voice_client_dave_announce_commit_transition
[2026-02-26 14:20:11] DEBUG: Processing commit
[2026-02-26 14:20:11] DEBUG: Successfully processed MLS commit, updating state; our leaf index is 0; current epoch is 1
[2026-02-26 14:20:11] DEBUG: process_mls_group_rosters of size: 2
[2026-02-26 14:20:11] DEBUG: Added user to MLS Group: 414646792567914506
[2026-02-26 14:20:11] DEBUG: Added user to MLS Group: 1445451591900463288
[2026-02-26 14:20:11] DEBUG: Ready to execute transition 0
[2026-02-26 14:20:11] DEBUG: Updating MLS ratchets for 2 user(s)
[2026-02-26 14:20:11] DEBUG: Inserting decryptor key ratchet for NEW user: 414646792567914506, protocol version: 1
[2026-02-26 14:20:11] DEBUG: Setting key ratchet for sending audio...
[2026-02-26 14:20:11] INFO: New E2EE Privacy Code: 72739 18640 25685 16453 76920 69812 
[2026-02-26 14:20:14] DEBUG: Retrieving key for generation 0 from hash ratchet
[2026-02-26 14:20:18] DEBUG: Unhandled event: VOICE_CHANNEL_START_TIME_UPDATE, {"d":{"guild_id":"414647568111239169","id":"414647568564486158","voice_start_time":1772115617},"op":0,"s":18,"t":"VOICE_CHANNEL_START_TIME_UPDATE"}
[2026-02-26 14:20:18] WARN: Voice session error: 4014 on channel 1464859146804396157: Disconnected
[2026-02-26 14:20:18] ERROR: This is a non-recoverable error, giving up on voice connection
[2026-02-26 14:20:18] WARN: Reached max loops whilst attempting to read from the websocket. Starting a full reconnection.
[2026-02-26 14:20:18] DEBUG: Sending op 4 to join VC, guild 414647568111239169 channel 1464859146804396157 WITH DAVE
LOOP FINISHED SINCE VC IS UNAVAILABLE
[2026-02-26 14:20:19] DEBUG: Connecting voice for guild 414647568111239169 channel 1464859146804396157
[2026-02-26 14:20:19] DEBUG: Unhandled event: VOICE_CHANNEL_START_TIME_UPDATE, {"d":{"guild_id":"414647568111239169","id":"414647568564486158","voice_start_time":null},"op":0,"s":22,"t":"VOICE_CHANNEL_START_TIME_UPDATE"}
[2026-02-26 14:20:19] DEBUG: Connecting new voice session (DAVE: Enabled)...
[2026-02-26 14:20:19] WARN: Voice session error: 4006 on channel 1464859146804396157: Session no longer valid
[2026-02-26 14:20:19] ERROR: This is a non-recoverable error, giving up on voice connection
[2026-02-26 14:20:19] WARN: Reached max loops whilst attempting to read from the websocket. Starting a full reconnection.
[2026-02-26 14:20:19] DEBUG: Sending op 4 to join VC, guild 414647568111239169 channel 1464859146804396157 WITH DAVE
```

</details>

<details>
<summary>program just crashed, expand for log</summary>

```text
[2026-02-26 14:10:44] DEBUG: Cluster: 997 of 1000 session starts remaining
[2026-02-26 14:10:44] INFO: Auto Shard: Bot requires 1 shard
[2026-02-26 14:10:44] DEBUG: Starting with 1 shards...
[2026-02-26 14:10:44] DEBUG: Connecting new session...
[2026-02-26 14:10:45] INFO: Shard id 0 (1/1) ready!
[2026-02-26 14:10:45] DEBUG: Resume URL for session e900f52337af1e08dd536e15953967cf is wss://gateway-us-east1-c.discord.gg (host: gateway-us-east1-c.discord.gg)
[2026-02-26 14:10:49] DEBUG: Shards started.
[2026-02-26 14:11:03] DEBUG: Sending op 4 to join VC, guild 414647568111239169 channel 1464859146804396157 WITH DAVE
[2026-02-26 14:11:04] DEBUG: Connecting voice for guild 414647568111239169 channel 1464859146804396157
[2026-02-26 14:11:04] DEBUG: Connecting new voice session (DAVE: Enabled)...
[2026-02-26 14:11:05] DEBUG: Voice websocket established; UDP endpoint: 104.29.158.39:19312 [ssrc=3207] with 2 modes
[2026-02-26 14:11:05] DEBUG: New of clients in voice channel: 1 total is 1
[2026-02-26 14:11:05] DEBUG: Creating a new MLS session
[2026-02-26 14:11:05] DEBUG: Resetting MLS session
[2026-02-26 14:11:05] DEBUG: Initializing MLS session with protocol version 1 and group ID 1464859146804396157
[2026-02-26 14:11:05] DEBUG: Created MLS leaf node
[2026-02-26 14:11:05] DEBUG: Cannot create MLS group without external sender
[2026-02-26 14:11:05] DEBUG: voice_client_dave_mls_external_sender
[2026-02-26 14:11:05] DEBUG: Unmarshalling MLS external sender
[2026-02-26 14:11:05] DEBUG: Creating a pending MLS group
[2026-02-26 14:11:05] DEBUG: Created a pending MLS group
[2026-02-26 14:11:05] DEBUG: voice_client_dave_mls_proposals
[2026-02-26 14:11:05] DEBUG: Processing MLS proposals message of 498 bytes
[2026-02-26 14:11:05] DEBUG: Prepared commit/welcome/next state for MLS group from received proposals
[2026-02-26 14:11:05] DEBUG: voice_client_dave_announce_commit_transition
[2026-02-26 14:11:05] DEBUG: Processing commit
[2026-02-26 14:11:05] DEBUG: Successfully processed MLS commit, updating state; our leaf index is 0; current epoch is 1
[2026-02-26 14:11:05] DEBUG: process_mls_group_rosters of size: 2
[2026-02-26 14:11:05] DEBUG: Added user to MLS Group: 414646792567914506
[2026-02-26 14:11:05] DEBUG: Added user to MLS Group: 1445451591900463288
[2026-02-26 14:11:05] DEBUG: Ready to execute transition 0
[2026-02-26 14:11:05] DEBUG: Updating MLS ratchets for 2 user(s)
[2026-02-26 14:11:05] DEBUG: Inserting decryptor key ratchet for NEW user: 414646792567914506, protocol version: 1
[2026-02-26 14:11:05] DEBUG: Setting key ratchet for sending audio...
[2026-02-26 14:11:05] INFO: New E2EE Privacy Code: 76665 53434 95288 02054 18871 75100 
[2026-02-26 14:11:09] DEBUG: Retrieving key for generation 0 from hash ratchet
[2026-02-26 14:11:20] DEBUG: Disconnecting voice, guild: 414647568111239169
LOOP FINISHED SINCE VC IS UNAVAILABLE
[2026-02-26 14:11:27] DEBUG: Sending op 4 to join VC, guild 414647568111239169 channel 1464859146804396157 WITH DAVE
[2026-02-26 14:11:29] DEBUG: Connecting voice for guild 414647568111239169 channel 1464859146804396157
[2026-02-26 14:11:29] DEBUG: Connecting new voice session (DAVE: Enabled)...
[2026-02-26 14:11:29] DEBUG: Voice websocket established; UDP endpoint: 104.29.158.39:19312 [ssrc=3210] with 2 modes
[2026-02-26 14:11:30] DEBUG: New of clients in voice channel: 1 total is 1
[2026-02-26 14:11:30] DEBUG: Creating a new MLS session
[2026-02-26 14:11:30] DEBUG: Resetting MLS session
[2026-02-26 14:11:30] DEBUG: Initializing MLS session with protocol version 1 and group ID 1464859146804396157
[2026-02-26 14:11:30] DEBUG: Created MLS leaf node
[2026-02-26 14:11:30] DEBUG: Cannot create MLS group without external sender
[2026-02-26 14:11:30] DEBUG: voice_client_dave_mls_external_sender
[2026-02-26 14:11:30] DEBUG: Unmarshalling MLS external sender
[2026-02-26 14:11:30] DEBUG: Creating a pending MLS group
[2026-02-26 14:11:30] DEBUG: Created a pending MLS group
[2026-02-26 14:11:30] DEBUG: voice_client_dave_mls_proposals
[2026-02-26 14:11:30] DEBUG: Processing MLS proposals message of 498 bytes
[2026-02-26 14:11:30] DEBUG: Prepared commit/welcome/next state for MLS group from received proposals
[2026-02-26 14:11:30] DEBUG: voice_client_dave_announce_commit_transition
[2026-02-26 14:11:30] DEBUG: Processing commit
[2026-02-26 14:11:30] DEBUG: Successfully processed MLS commit, updating state; our leaf index is 0; current epoch is 1
[2026-02-26 14:11:30] DEBUG: process_mls_group_rosters of size: 2
[2026-02-26 14:11:30] DEBUG: Added user to MLS Group: 414646792567914506
[2026-02-26 14:11:30] DEBUG: Added user to MLS Group: 1445451591900463288
[2026-02-26 14:11:30] DEBUG: Ready to execute transition 0
[2026-02-26 14:11:30] DEBUG: Updating MLS ratchets for 2 user(s)
[2026-02-26 14:11:30] DEBUG: Inserting decryptor key ratchet for NEW user: 414646792567914506, protocol version: 1
[2026-02-26 14:11:30] DEBUG: Setting key ratchet for sending audio...
[2026-02-26 14:11:30] INFO: New E2EE Privacy Code: 72917 95449 29884 45360 73583 77585 
[2026-02-26 14:11:36] DEBUG: Retrieving key for generation 0 from hash ratchet
[2026-02-26 14:11:45] DEBUG: Unhandled event: VOICE_CHANNEL_START_TIME_UPDATE, {"d":{"guild_id":"414647568111239169","id":"414647568564486158","voice_start_time":1772115105},"op":0,"s":17,"t":"VOICE_CHANNEL_START_TIME_UPDATE"}
[2026-02-26 14:11:45] WARN: Voice session error: 4014 on channel 1464859146804396157: Disconnected
[2026-02-26 14:11:45] ERROR: This is a non-recoverable error, giving up on voice connection
[2026-02-26 14:11:45] WARN: Reached max loops whilst attempting to read from the websocket. Starting a full reconnection.
[1]    493701 segmentation fault (core dumped)  ./a.out
```

</details>

### **To Reproduce**
You may use this example program or any robot that can keep streaming audio:

<details>
<summary>example reproduce robot</summary>

```cpp
#include <dpp/dpp.h>
#include <iomanip>
#include <sstream>
 
int main() {
    uint8_t* robot = nullptr;
    size_t robot_size = 0;
    std::ifstream input ("Robot.pcm", std::ios::in|std::ios::binary|std::ios::ate);
    if (input.is_open()) {
        robot_size = input.tellg();
        robot = new uint8_t[robot_size];
        input.seekg (0, std::ios::beg);
        input.read ((char*)robot, robot_size);
        input.close();
    }
    dpp::cluster bot("YOUR TOKEN");
    bot.on_log(dpp::utility::cout_logger());
    bot.on_slashcommand([&bot, robot, robot_size](const dpp::slashcommand_t& event) {
        if (event.command.get_command_name() == "join") {
            dpp::guild* g = dpp::find_guild(event.command.guild_id);
            if (!g->connect_member_voice(*event.owner, event.command.get_issuing_user().id)) {
                event.reply("You don't seem to be in a voice channel!");
                return;
            }
            event.reply("Joined your channel!");
        } else if (event.command.get_command_name() == "robot") {
            // !!!
            // The program is modified from https://dpp.dev/soundboard.html
            // ONLY IS COMMAND IS UPDATED using a thread to keep streaming audio
            // !!!
            dpp::voiceconn* v = event.from()->get_voice(event.command.guild_id);
            if (!v || !v->voiceclient || !v->voiceclient->is_ready()) {
                event.reply("There was an issue with getting the voice channel. Make sure I'm in a voice channel!");
                return;
            }
            dpp::discord_client* from = event.from();
            dpp::snowflake guild_id = event.command.guild_id;
            std::thread([from, guild_id, robot, robot_size]() {
                using namespace std::chrono;
                size_t offset = 0;
                // Use 60ms sleep as requested, send small chunks each iteration
                const size_t step_size = 48000 * 2 * 2 / 1000 * 60;
                while (true) {
                    try {
                        dpp::voiceconn* vc = from->get_voice(guild_id);
                        if (!vc || !vc->voiceclient || !vc->voiceclient->is_ready()) {
                            break;
                        }
                        size_t remaining = robot_size - offset;
                        size_t send = std::min(step_size, remaining);
                        vc->voiceclient->send_audio_raw((uint16_t*)(robot + offset), send);
                        offset += send;
                        if (offset >= robot_size) {
                            offset = 0; // restart from beginning
                        }
                    } catch (...) {
                        break;
                    }
                    // may introduce glitch since send request take time
                    std::this_thread::sleep_for(std::chrono::milliseconds(58));
                }
                std::cout << "LOOP FINISHED SINCE VC IS UNAVAILABLE" << std::endl;
            }).detach();
            event.reply("Played robot.");
        }
    });
 
    bot.on_ready([&bot](const dpp::ready_t & event) {
        if (dpp::run_once<struct register_bot_commands>()) {
            dpp::slashcommand joincommand("join", "Joins your voice channel.", bot.me.id);
            dpp::slashcommand robotcommand("robot", "Plays a robot noise in your voice channel.", bot.me.id);
            bot.global_bulk_command_create({ joincommand, robotcommand });
        }
    });
 
    bot.start(dpp::st_wait);
    return 0;
}
```

</details>

1. Run the example robot, and use /join to let it join with you 
2. After joined, use command /robot, you will hear from the bot (the sound may be glitched since i used a fixed delay time, or i did not set `satype_live_audio`)
3. Make sure you have the permission to move ppl to another channel, move the robot to another voice channel

**Expected behavior**
- either the robot moves back to original channel and if you call /robot again it will say im not in any channel
- or the program crashes

### **System Details:**
For robot server:
```
Operating System: Ubuntu 24.04.3 LTS              
          Kernel: Linux 6.8.0-94-generic
    Architecture: x86-64
 Hardware Vendor: Gigabyte Technology Co., Ltd.
  Hardware Model: B550I AORUS PRO AX
Firmware Version: F10
   Firmware Date: Fri 2020-09-18
    Firmware Age: 5y 5month 1w 2d
```
Discord client: Windows desktop client

### PR DESCRIPTION
**Pull request by Zhang-JK**
To fix issue #1553 
When moved to a new channel event (under `voice_state_update`) received, reset all connection and wait for new one (new connection will be established when event `voice_server_update` received)

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR. (please refer to the example test bot in issue)
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

### CODE REVIEW

**Comment by Jaskowicz1** [comment]
Gonna approve actions but I need to look a bit more at this when home.

Looks all good at a quick glance, just want to look a little more at this :)

File: src/dpp/events/voice_state_update.cpp [hunk 1]
```diff
@@ -70,6 +70,19 @@ void voice_state_update::handle(discord_client* client, json &j, const std::stri
 		if (vsu.state.channel_id.empty()) {
 			/* Instruction to disconnect from vc */
 			client->disconnect_voice_internal(vsu.state.guild_id, false);
+		} else if (client->get_voice(vsu.state.guild_id)->channel_id != 0 &&
```
Comment (braindigitalis) [inline src/dpp/events/voice_state_update.cpp]: I would avoid calling get_voice twice here. call it once, store it to a variable and check if it's null. it can return null.

pretty sure you can't have channel id == 0 in a get_voice return, have you seen that happen?

File: src/dpp/events/voice_state_update.cpp [hunk 2]
```diff
@@ -70,6 +70,19 @@ void voice_state_update::handle(discord_client* client, json &j, const std::stri
...
+		           vsu.state.channel_id != client->get_voice(vsu.state.guild_id)->channel_id) {
+			/* Instruction to connect to a different channel */
+			std::shared_lock lock(client->voice_mutex);
+			auto v = client->connecting_voice_channels.find(vsu.state.guild_id);
+			if (v != client->connecting_voice_channels.end()) {
+				voiceconn& connection = *v->second;
+				connection.disconnect();
```
Comment (braindigitalis) [inline src/dpp/events/voice_state_update.cpp]: pretty sure you have to remove the connection not just zero out it's fields.

**Review by braindigitalis — CHANGES_REQUESTED** [review]

File: src/dpp/events/voice_state_update.cpp (hunk 2 above)
Comment (braindigitalis) [reply src/dpp/events/voice_state_update.cpp]: you likely want disconnect_voice_internal

File: src/dpp/events/voice_state_update.cpp (hunk 1 above)
Comment (Zhang-JK) [reply src/dpp/events/voice_state_update.cpp]: updated, channel id in vc cannot be empty

File: src/dpp/events/voice_state_update.cpp (hunk 2 above)
Comment (Zhang-JK) [reply src/dpp/events/voice_state_update.cpp]: cannot call disconnect_voice_internal since it will notice discord to disconnect the voice channel. 

i updated here to remove the connection first and create a new one. tested on the example program in issue works fine

**Review by braindigitalis — APPROVED** [review]
