### PR TITLE
Fix/uncleared track meta on stop audio

### LINKED ISSUE #1124: dpp::discord_voice_client: track_meta is not cleared when stop_audio() is called
**Git commit reference**
89b43ba1445f99114f1c583529d01ad210918c35

**Describe the bug**
When voice client's stop_audio() is called, all 2-byte markers `0xFFFF` in `outbuf` are deleted, however `track_meta` vector is not cleared.

**To Reproduce**
1. Send a voice marker with metadata "ABC"
2. Call `stop_audio()`
3. Send another voice marker with metadata "DEF"
4. When `on_voice_track_marker()` callback is called by `DEF` marker, `event.track_meta` is `ABC`. One marker was inserted after `stop_audio()`, but `track_meta` size is 2, so `event.track_meta` contains metadata from "deleted" marker.

**Expected behavior**
All markers metadata should be deteled when `stop_audio()` is called.
The second marker in the example should have `event.track_meta` = "DEF" instead of "ABC"

**System Details:**
 - Linux rpi4 6.1.0-rpi6-rpi-v8 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux
 - Desktop Discord Client

**Suggested solution**
Adding `this->track_meta.clear()` at `/src/dpp/discordvoiceclient.cpp` at line 695.

### PR DESCRIPTION
**Pull request by Neko-Life**
## Changes in this PR
- Close #1124 
- Avoid hardcoded size check
- Faster erase of outbuf when skipping marker
- Tested on Musicat -alpha, no problem so fat

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

### CODE REVIEW

File: src/dpp/discordvoiceclient.cpp [hunk 1]
```diff
@@ -1165,20 +1167,29 @@ uint32_t discord_voice_client::get_tracks_remaining() {
...
-		outbuf.erase(outbuf.begin());
-	}
-	if (outbuf.size()) {
-		/* Remove the actual track marker out of the buffer */
-		outbuf.erase(outbuf.begin());
+	if (!outbuf.empty()) {
+		/* Find the first marker to skip to */
+		auto i = std::find_if(outbuf.begin(), outbuf.end(), [](const voice_out_packet &v){
+				return v.packet.size() == sizeof(uint16_t) && (*((uint16_t*)(v.packet.data()))) == AUDIO_TRACK_MARKER;
+				});
```
Comment (Jaskowicz1) [inline src/dpp/discordvoiceclient.cpp:1174]: I'd just un-indent this `});` by one tab (so it's inline with `std::find_if`) so it's better looking :)

**Review by Jaskowicz1 — CHANGES_REQUESTED** [review]

File: src/dpp/discordvoiceclient.cpp (hunk 1 above)
Comment (Neko-Life) [reply src/dpp/discordvoiceclient.cpp]: done

**Review by Mishura4 — APPROVED** [review]
👍

File: src/dpp/discordvoiceclient.cpp [hunk 2]
```diff
@@ -1165,20 +1167,29 @@ uint32_t discord_voice_client::get_tracks_remaining() {
...
-	while (!outbuf.empty() && outbuf[0].packet.size() != sizeof(uint16_t) && (*((uint16_t*)(outbuf[0].packet.data()))) != AUDIO_TRACK_MARKER) {
-		outbuf.erase(outbuf.begin());
-	}
-	if (outbuf.size()) {
-		/* Remove the actual track marker out of the buffer */
-		outbuf.erase(outbuf.begin());
+	if (!outbuf.empty()) {
+		/* Find the first marker to skip to */
+		auto i = std::find_if(outbuf.begin(), outbuf.end(), [](const voice_out_packet &v){
+				return v.packet.size() == sizeof(uint16_t) && (*((uint16_t*)(v.packet.data()))) == AUDIO_TRACK_MARKER;
```
Comment (Mishura4) [inline src/dpp/discordvoiceclient.cpp:1173]: Actually it looks like we still have indentation issues with this lambda here, there is an extra tab

File: src/dpp/discordvoiceclient.cpp [hunk 3]
```diff
@@ -1165,20 +1167,29 @@ uint32_t discord_voice_client::get_tracks_remaining() {
...
+			 });
```
Comment (Mishura4) [inline src/dpp/discordvoiceclient.cpp:1174]: And here an extra tab + space

**Review by Mishura4 — CHANGES_REQUESTED** [review]

File: src/dpp/discordvoiceclient.cpp (hunk 2 above)
Comment (Neko-Life) [reply src/dpp/discordvoiceclient.cpp]: it's default vim indent behavior with correct shiftwidth and tabstop, maybe we need to create .clang-format file to make formatting easier across different editor

File: src/dpp/discordvoiceclient.cpp (hunk 3 above)
Comment (Neko-Life) [reply src/dpp/discordvoiceclient.cpp]: yes i added the space, fixed

**Review by Mishura4 — APPROVED** [review]
👍 LGTM ship it

**Comment by Mishura4** [comment]
@Jaskowicz1

File: src/dpp/discordvoiceclient.cpp (hunk 2 above)
Comment (Mishura4) [reply src/dpp/discordvoiceclient.cpp]: Use a real IDE like Visual Studio catsuit

**Review by Jaskowicz1 — APPROVED** [review]

File: src/dpp/discordvoiceclient.cpp (hunk 2 above)
Comment (Neko-Life) [reply src/dpp/discordvoiceclient.cpp]: i mean u can just export the built-in formatting config of VS into an actual .clang-format file r8? surely such "full featured real IDE" like VS can do a simple export image image image
