### PR TITLE
fix: base64 sslclient key

### LINKED ISSUE #714: Bot is unable to properly connect to certain Discord voice servers
**Git commit reference**
cd5b9cab3fb6a49ece575e0f86475268f886766b

**Describe the bug**
The problem is that `on_voice_ready` callback is not called when bot connects to certain voice channels.
Example of successful voice server connection:
1. DPP logs show this:
`DEBUG: Sending op 4 to join VC, guild xxx channel xxx`
`DEBUG: Connecting voice for guild xxx channel xxx`
`DEBUG: Connecting new voice session...`
`DEBUG: Voice websocket established; UDP endpoint: xxx.xxx.xxx.xxx:xxx [ssrc=xxx] with 7 modes`
`DEBUG: External IP address: xxx.xxx.xxx.xxx`
2. Bot connects with following request:
`GET /?v=4 HTTP/1.1`
`Host: russia8508.discord.media`
`pragma: no-cache`
`User-Agent: DPP/0.1`
`Upgrade: WebSocket`
`Connection: Upgrade`
`Sec-WebSocket-Key: xxx`
`Sec-WebSocket-Version: 13`
3. Server responds with HTTP 101 response:
`HTTP/1.1 101 Switching Protocols`
`Connection: upgrade`
`sec-websocket-accept: xxx`
`upgrade: websocket`
`CF-Cache-Status: DYNAMIC`
`Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=xxx"}],"group":"cf-nel","max_age":604800}`
`NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}`
`Strict-Transport-Security: max-age=15552000; includeSubDomains; preload`
`X-Content-Type-Options: nosniff`
`Server: cloudflare`
`CF-RAY: xxx-DME`
4. Server sends JSON payload:
`1{"op":8,"d":{"v":4,"heartbeat_interval":13750.0}}`
`Connection: upgrade`
`sec-websocket-accept: xxx`
`upgrade: websocket`
`CF-Cache-Status: DYNAMIC`
`Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=xxx"}],"group":"cf-nel","max_age":604800}`
`NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}`
`Strict-Transport-Security: max-age=15552000; includeSubDomains; preload`
`X-Content-Type-Options: nosniff`
`Server: cloudflare`
`CF-RAY: xxx-DME`
5. Connection proceeds. `on_voice_ready` callback is called.

Example of erroneous voice server connection in different Discord guild:
1. DPP logs show this:
`DEBUG: Sending op 4 to join VC, guild xxx channel  xxx`
`DEBUG: Connecting voice for guild xxx channel xxx`
Nothing happens after that.
2. Bot connects with following request:
`GET /?v=4 HTTP/1.1`
`Host: tel-aviv10001.discord.media`
`pragma: no-cache`
`User-Agent: DPP/0.1`
`Upgrade: WebSocket`
`Connection: Upgrade`
`Sec-WebSocket-Key: xxx`
`Sec-WebSocket-Version: 13`
3. Server responds with HTTP 400 response:
`HTTP/1.1 400 Bad request`
`Content-Type: text/html`
`Transfer-Encoding: chunked`
`Connection: keep-alive`
`Cache-Control: no-cache`
`CF-Cache-Status: DYNAMIC`
`Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=xxx"}],"group":"cf-nel","max_age":604800}`
`NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}`
`Strict-Transport-Security: max-age=15552000; includeSubDomains; preload`
`X-Content-Type-Options: nosniff`
`Server: cloudflare`
`CF-RAY: xxx-DME`
`5a`
`<html><body><h1>400 Bad request</h1>`
`Your browser sent an invalid request.`
`</body></html>`
4. By design of `dpp::discord_voice_client::thread_run()` function bot tries to reconnect. Steps 2 and 3 are repeated infinitely.
It may be important to mention that in Discord client bot actually connects to voice channel and sits there even when HTTP 400 error occurs.

**To Reproduce**
Issue appears to only occur when bot connects to `tel-avivXXXXX.discord.media` Discord voice servers. The problematic servers do work in Discord desktop clients, so I think the problem is with the library.
1. Connect to voice channel that is served by `tel-avivXXXXX.discord.media` voice server.
2. Make the bot connect to it, for example call `dpp::guild::connect_member_voice()`.
3. Observe that `on_voice_ready` callback is never called although bot connects to voice channel in Discord UI.

**Expected behavior**
Bot should properly connect to voice server and `on_voice_ready` callback should be called.

**System Details:**
 - Tried it on both 
`Linux PC 5.15.90.1-microsoft-standard-WSL2 #1 SMP x86_64 x86_64 x86_64 GNU/Linux`
and
`Linux rpi4 6.1.21-v8+ #1642 SMP PREEMPT aarch64 GNU/Linux`
OSes.
 - Desktop Discord Client was used for testing

Some of my assumptions/terms may be wrong because I tried to get how DPP source code works manually.

### PR DESCRIPTION
**Pull request by braindigitalis**
fixes #714 

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

### CODE REVIEW

**Review by Mishura4 — APPROVED** [review]

**Comment by Jaskowicz1** [comment]
All good :)

File: src/dpp/wsclient.cpp [hunk 1]
```diff
@@ -38,11 +39,12 @@ constexpr size_t MAXHEADERSIZE = sizeof(uint64_t) + 2;
 
 websocket_client::websocket_client(const std::string &hostname, const std::string &port, const std::string &urlpath, ws_opcode opcode)
 	: ssl_client(hostname, port),
-	key(std::to_string(time(nullptr))),
 	state(HTTP_HEADERS),
 	path(urlpath),
 	data_opcode(opcode)
 {
+	key = std::to_string(time(nullptr));
+	key = base64_encode((const unsigned char*)key.c_str(), key.length());
```
Comment (Mishura4) [inline src/dpp/wsclient.cpp:47]: This should be a reinterpret_cast (it will also silence the warning)

**Review by Mishura4 — CHANGES_REQUESTED** [review]

**Review by Mishura4 — APPROVED** [review]
